server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lr_database?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

  mail:
    protocol: smtps
    host: smtp.163.com
    port: 465
    username: 18967220636@163.com
    password: UUvD283xqxYEKyAi
    default-encoding: UTF-8
    from: 18967220636@163.com
    properties:
      mail.smtp.socketFactoryClass: javax.net.ssl.SSLSocketFactory

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      accessKeyId: ${ALIBABA_ACCESS_KEY_ID}
      accessKeySecret: ${ALIBABA_ACCESS_KEY_SECRET}
      bucketName: oss-symbol


short-link:
  domain:
    default: buaa.link:8000
  stats:
    locale:
      amap-key: 49c977bb4eae8868b2a2e6ccc851d507

alipay:
  appId: 9021000142652477
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCK03wI2o/rR/FufMiegFN4hkfhvA8D8yViDGg1d3AOVECGoJGKl9pKJDUr6pgsO7ueJ/Quo0VBQc3WlCg481Im533vEhkQCLQn9WI/l1Ep/slG27KgYqNnwb/lX89mUU/3IoTYYAKfSenlwMFL2IdUFYXoDR2WBMxSaUy2KfnqSMOaV2INgFE2yFghsJu+a5jtnsIy+T5zEw4M0LGkiJxKhbZIUahVH8IOvgbe/QTVD+A5nlKFC/amIO4DWfKb4mVF9y9f9au4dV6mBDdkZDMr7Oq29TF2+JT4UX9W1Le0T4PIFzjfc+uff/UOmxHAYKP3GpykVT8PwdO9q+zckQXzAgMBAAECggEAYEfEIi/S2I6Qttv8F1FQkqoueDQBBfA/4PxR2aL4KDfueHAsAD7IudratZaB60uSF2IGS8IYaeXFaChgrP6z3x91i7S1hRVEPOJGPWwockOuPGJqRCmkwnTxLZeBM6j5GKDsGVSc/PQ6L4m7hWqqkHpM4F8YQc8aFZ3KAhyiowTDDofV1PK3SssoVFgWnUZm7ieaB8fGfnofvZpoE+zQElJmp3cawZLW1GkNZx5vdBBNe+r+qyiyvxstaZxJ2DZr8ylAKGFNrR0ciKsLawaJ7lntSy+AYwwcRKp8+o3jvcfFxHRRZyinf/rWgZR0Be1TaKXh/DYsxuI35D2gn87c4QKBgQDd0Ns8M5uCAlrh2mzYBykPNAbEi3qH/6AfN7U6FEixETxeyfQY0uq19Xx7IgrSHd9ox3AWXFNBCdNILGPqDeI56dTQkU3xBI7G4LZIcC0R9sQy6vSTpv+4VXwOocz/SMefCSL1VGFvqu2aYB7KN4lB5B7JiBf7xdZHwyoR6Oe6vwKBgQCgOH4sZxqnKWtk7wPmYXZ3fuQGq2HijPLXcthXyLm8DWh4wkI+G0jZJEYE2rsN9M7n+nrdbxV/KI9FywLPgf22eBvc/AVZbigwVC/4ERB20FdmjNNs14oFkT7SqJPt+VUuxpo0NCpOIJSpJg3av/Z9DZeINhRYGY4xQwr8bBVFzQKBgQDYFfK9PvkrOegXRZXrDW6uZNyC8+22Nwxh3P8rST9XX5cUMGEfHbmQ8UkHGy63amqNxFwpLF/eaBfvo27iQAw2ptivJh5rwSjmDVsGTmFZsq+HeuQwQuuzQ3PLPUxbFSeCgoAPxtf01OsLDMBx9pA8JGLpqS7UEvKgjjuZnu7AOQKBgCuBC2l9GXSYP4vphnKQtj0eHEZfVLXSNcIgcfPsEdqo/VwEyz3X5MDpI4X/6liQx3mfvqrPldOwLK7zv7CeiEh6dn5bhAxTZ+Avi9Lct067pW+3/1SHdferB5blpT0xvVp1HLveCjqqiBMhvRNPmls8TI/0tzNwxPZFUP9XTbNlAoGAJ7Woe45e3wtT2vcURf8gAnvj6WnBWLXnUZJmN4TNyb8+6NILGhAc+Q3AKYVjKpEFLciy5k6SSFC+dfi4IWnN21oWCK/FGP4abYtTyXMBvL3oVwNnlU7ar4nQVeG68Dl9cy7RnLi9xzU03kat/qdY6aJE5PQybFv65UOtb1WvaLE=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAitvfdN+qoAUEpWhmoJsTbcbNzEhEXT6QS/5blKdG0X92DvD3eYzx2wdieTAs7noXDPnthG9PrtaHXxAdW0DBUt7RWUU8fSK+YAVhDG7w6Vgij2IGHF/44kaL5NdzUhQ/h2ZxtpnPrPYVVuKDRSjJvzZ7zBc+Wf6kMfhEDtm7EES5vA62E/3/0PzgA4eH0zTIjdM+jIloL9USBwlTIWy6i9Tz4E/Yh0PmYBMbETBYzntgp7Y6Y2NCrAhE1nNalipy1TWXkUtlujTEnjVahQ7lgkLqFubwi4kCOu5ZmTcJJiqNcz0LoqO4hjoGiTGmFWmN7+zi4NOYvUOndhgO+MVSkwIDAQAB
  notifyUrl: http://buaalink.natapp1.cc/api/short-link/order/notify